language: ruby

cache:
  apt: true
  bundler: true # caching to speed up dependency installation
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

rvm:
- 2.4.1

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site
  --check-external-hash
  --check-opengraph
  --check-sri
  --check-html
  --check-img-http
  --enforce-https
  --timeframe 4w
